import "@/app/globals.css";
import dynamic from "next/dynamic";
import { Roboto } from "next/font/google";
const ThemeProvider = dynamic(() => import("@/components/theme-provider"));

import "leaflet/dist/leaflet.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "EWATER - HOME PAGE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
